### PR TITLE
Generalize all `operator<<()`s (every container should now be accepted)

### LINKED ISSUE #4: No custom template argument support
Say if I had something like this:

``` c++
  class mlg_pro_360_noscope;                     // Defined elsewhere
  class my_super_mlg_pro_360_noscope_allocator;  // Defined elsewhere
  int main() {
    std::vector<mlg_pro_360_noscope, my_super_mlg_pro_360_noscope_allocator> vec;
    /// Add stuff to `vec` somehow here ///
    std::cout << vec << '\n';
  }
```

It would give me an error, since your `operator<<()`s accept `const std::vector<T, std::allocator<T>> &` only.
Note, that this applies for all other `std` containers as well

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Closes #4

Also used _a_  formatting style, which can be found [here](https://gist.github.com/nabijaczleweli/db680f910f914b681ef3)

### CODE REVIEW

**Comment by Anmol-Singh-Jaggi** [comment]
@nabijaczleweli Thanks for the improvements, but since I am not well-versed with templates, I am unable to properly understand the code.
And since I cannot understand the code, I fear that I will have trouble modifiying or introducing new changes to it in the future.
But as soon as I learn enough about templates, I'll merge this request.

**Comment by nabijaczleweli** [comment]
A few non-trivial things used:
- http://en.cppreference.com/w/cpp/language/parameter_pack
- http://en.cppreference.com/w/cpp/language/template_parameters (scroll down to "Template template parameter" section)

Hope it helps

**Comment by Anmol-Singh-Jaggi** [comment]
Thanks a lot !

**Comment by nabijaczleweli** [comment]
Any status on this?

**Comment by Anmol-Singh-Jaggi** [comment]
I still haven't got time to study about all this template wizardry. But soon...

**Comment by nabijaczleweli** [comment]
Any update on this?

**Comment by Anmol-Singh-Jaggi** [comment]
It's been a while since I used C++ (I've switched to Python as my primary language), so my knowledge about C++ has deteriorated even further, which means I'm having more difficulty understanding it than the previous time. Also, I want the code to remain compatible with old compilers.

**Pull request closed without merging**
